# Generated by Django 5.2.8 on 2025-11-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turniej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('liczba_graczy', models.IntegerField(max_length=3)),
                ('aktualna_liczba', models.IntegerField(max_length=3)),
                ('nagroda_pieniezna', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('epic_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('platforma', models.CharField(choices=[('PC', 'Komputer'), ('XBOX', 'Xbox'), ('PS', 'PlayStation'), ('SWITCH', 'Nintendo Switch')], default='PC', max_length=20)),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zgloszenia', to='turniej.turniej')),
            ],
        ),
    ]
